### ISSUE TITLE
Cog memory leak

### ISSUE THREAD

**Issue by lilveg** [Igalia/cog#65]
Hello!

I am experiencing a memory leak in Cog. It's memory usage grows by about 25 MB/hour. The attached graph shows the available system memory along with with the memory consumed by Cog, WPEWebProcess and WPENetworkProcess individually, over a period of about 20 hours.

![cog-memory](https://user-images.githubusercontent.com/3798823/46790918-396f5a00-cd40-11e8-8b9c-7b48f084813e.png)

I am running a Qualcomm Snapdragon SD-410, with the latest Cog and WPE from [meta-webkit](https://github.com/Igalia/meta-webkit) as of yesterday (b12d42). This means commit 063df1 of Cog and version 2.22.0-r0 of WPEWebKit.

I am starting cog with these variables and arguments

```
[Service]
Environment=XDG_RUNTIME_DIR=/data/xdg_runtime_dir
Environment=COG_PLATFORM_FDO_VIEW_FULLSCREEN=1
Environment=WEBKIT_INSPECTOR_SERVER=0.0.0.0:2999
Environment=WPE_RAM_SIZE=128m
Environment=WPE_POLL_MAX_MEMORY=databaseprocess:50m,networkprocess:100m,webprocess:300m,rpcprocess:50m
Environment=MSE_MAX_BUFFER_SIZE=audio:2m,video:15m,text:1m
ExecStart=/usr/bin/cog -P fdo --enable-write-console-messages-to-stdout=true <url>
```

The page being displayed is of relatively low-resolution images scrolling horizontally using canvas, but the issue has also been observed when using css transforms.

Any help in finding the source of this problem is greatly appreciated!

**Comment by lilveg** [comment]
Hello Adrian,

The screen is 1280x1024. The canvas-based carousel runs at between 20 and 30 FPS, depending on how many images are on the screen.

**Comment by lilveg** [comment]
I ran a test over the weekend, on the site that uses CSS transformations. Curiously, Cog consumes memory in a steep curve until it reaches 300 MB, then flattens out. This flattening corresponds with the system running very low on available memory, yet the fact that the memory consumption becomes so flat leads me to wonder if some kind of memory limit has been reached in Cog.

![cog](https://user-images.githubusercontent.com/3798823/46945735-ec5bf280-d075-11e8-8b40-ec95602873e1.png)

Near the end of the graph, WPEWebProcss seems to crash, and the screen was blank this morning. I assume this happened to due lack of memory.

**Comment by aperezdc** [comment]
A small leak was fixed in the FDO backend recently (see https://github.com/Igalia/WPEBackend-fdo/pull/31), I wonder if it might be related :thinking: 

@lilveg Is there any chance you could re-run your test with the patch applied? Note that the fix is also available in the `wpebackend-fdo-1.0` branch, which I think is the version you were (are?) probably using.

**Comment by aperezdc** [comment]
I am going to close this issue for now, as it looks like the issue is gone—or at least nobody has been able to reproduce it anymore. If @lilveg or someone else can still hit the problem with current versions, we can always reopen this issue later :smiley_cat:

**Comment by vnd** [comment]
There's a memory leak during video playback with recent cog/wpewebkit on i.MX6DL platform:
https://github.com/WebPlatformForEmbedded/WPEWebKit/issues/1191

(not sure which project is better suited for opening that issue, so just referencing it here)

**Comment by stfnzl** [comment]
Hi!

We are experiencing (most likely) the same issue: we can reproduce it with the following transform

```css
.scrolling-text {
    animation: scroll-left 200 linear infinite;
    transform: translate3d(0, 0, 0);
}

@keyframes scroll-left {
    0% {
        transform: translate3d(1600px, 0, 0);
    }
    100% {
        transform: translate3d(-100%, 0, 0);
    }
}
```

**Comment by oaquique** [comment]
Confirming this still reproduces in 2026 on current versions, with the same
  ~25 MB/hr signature.

  **Environment**
  - Hardware: Raspberry Pi 5 (4 GB) on NVMe
  - OS: Debian 13 Trixie (aarch64)
  - `cog` 0.18.4-1+b1 (Debian build)
  - `libwpewebkit-2.0-1` 2.50.6
  - `libwlroots-0.18` 0.18.2-3+rpt4+b1
  - Workload: single internal kiosk page, one tab, never navigated, runs continuously
  - Invocation: `cog --platform=drm --platform-params=renderer=gles,rotation=1
    --bg-color=#000000 http://localhost:3000`
    (`WPE_ENABLE_MEMORY_PRESSURE=1` is set in the unit; no compositor — direct KMS)

  **Observed**
  - WPEWebProcess RSS grows linearly at **~25–30 MB/hr**, sustained
  - Measured over an 8.5-hour window between two restarts: memory went from
    ~25.2% → ~30.3% on the 4 GB device (~230 MB delta)
  - Identical signature was visible on the same React app running under
    WPE 2.42.x on a Raspberry Pi 4 (3.5 GB) — different hardware, same rate band,
    so it's a property of the engine rather than the host

  **Ruled out app-side**
  Audited the React app for common kiosk-leak patterns: all `setInterval`/`setTimeout`
  are paired with cleanup, all `AbortController`s aborted on unmount, all
  `addEventListener`s removed, web worker terminated, no `requestAnimationFrame`,
  no observers, no dynamic `Image`/`AudioContext`/`WebGL`, no framer-motion or
  react-spring. useEffect dep arrays correct. The app's not the source.

  **Mitigation we run**
  A `systemctl --user restart kiosk.service` from cron at 3 AM daily. With the
  mitigation in place, peak memory before each restart sits around ~42% of 4 GB —
  no functional impact, no OOM risk. Just a workaround.

  **Possibly related upstream**
  - [WPEWebKit#1569](https://github.com/WebPlatformForEmbedded/WPEWebKit/issues/1569)
    — RSS climb on long-running React page
  - [WPEWebKit#1363](https://github.com/WebPlatformForEmbedded/WPEWebKit/issues/1363)
    — JSC GC not reclaiming on long-running pages, plausibly a root cause

  Happy to provide more traces if useful — let me know what would be most helpful
  (heap snapshot via remote inspector, `webkit_web_context_garbage_collect_*` test
  results, `Memory.dump` from inspector, etc.).

**Comment by daviesjamesdaniel** [comment]
Hey All

Been chasing this on a Raspberry Pi 3B kiosk deployment 
Wayland, cog 0.18.4 from Debian trixie, WPE WebKit 2.48.3) and I might have stumbled on the root cause at least for my setup and hopefully explains the pattern others have seen 

`keyboard_on_keymap()` in `platform/wayland/cog-platform-wl.c` overwrites `seat->xkb.keymap` and `seat->xkb.state` every time the compositor sends wl_keyboard.keymap without releasing the previous objects first 

On my compositor (labwc) this event is being fired repeatedly during normal operation therefore greatly increasing the leak effects 

Confirmed with a heaptrack which in a period of 2.5 minutes showed 76% of leaked bytes were traced directly to that call site 

The fix mirrors what is already done in the teardown in cog-utils-wl.c 
`g_clear_pointer(&seat->xkb.state, xkb_state_unref);`
`g_clear_pointer(&seat->xkb.keymap, xkb_keymap_unref);`

I have it running on my kiosk currently and early results are very promising with a leak rate prior to the fix of ~ 170 MB / hr and after running for more than 16 hours it is completely flat 

Will let this run for a few days I think just to be sure of things and then happy to raise a PR. I want to be sure of the diagnosis given the age of this issue and a few upstream fixes that have then not fixed things.

Thanks
Dan

**Comment by daviesjamesdaniel** [comment]
Hey All

Quick update things are looking very promising I had around 60 hours and during that time the heap RSS has stayed completely flat at ~1.8MB 

Unfortunately I hit an unrelated bug with wl_output that crashed the connection and therefore reset the timer (PR raised for this under 796) so will restart the clock and check things are good before proposing a PR for this 

Thanks
Dan

**Comment by daviesjamesdaniel** [comment]
Hey All 

Things still looking good so will be raising a PR for this shortly 
Completed ~60 hours before hitting the issue under 796 and now over 100 hours uptime with the fix since then 

In both soaks the heap has remained flat
